tabs:
  main:
    display: Hauptteil
    sections:
      -
        fields:
          -
            handle: title
            field:
              type: text
              required: true
          -
            import: products
            prefix: product_
  sidebar:
    display: Sidebar
    sections:
      -
        fields:
          -
            handle: slug
            field:
              type: slug
              localizable: true
              validate: 'max:200'
title: Produkte
